### ISSUE TITLE
Module Manager: execTransactionFromModule does not emit module events

### ISSUE THREAD

**Issue by zakrad** [bcnmy/scw-contracts#137]
I noticed that in the module manager's `execTransactionFromModule` function, it directly uses the `_execute` function from the executor contract. However, this setup doesn't emit any of module events when a transaction succeeds or fails.

I'm wondering why we're not using the `_executeFromModule` function, like we do in the `execBatchTransactionFromModule` method, for consistency.

**Comment by Aboudjem** [comment]
Hey @Zakrad 😊
thank you for pointing this out. The design choice was made for specific reasons, but your observation about consistency is valid. We'll review the implementation and consider making adjustments in future iterations. Thanks again your feedback is valuable to us! 👍

Can you please check and address this @filmakarov ? thanks

**Comment by livingrockrises** [comment]
we could potentially add below code [here](https://github.com/bcnmy/scw-contracts/blob/main/contracts/smart-account/base/ModuleManager.sol#L109)

```
if (success) {
            emit ModuleTransaction(msg.sender, to, value, data, operation);
            emit ExecutionFromModuleSuccess(msg.sender);
        } else {
            emit ExecutionFromModuleFailure(msg.sender);
        }
```

can check this diff view. will get it internally reviewed with the team 
https://github.com/bcnmy/scw-contracts/pull/154/files

**Comment by zakrad** [comment]
It's also not possible to specify `txGas` for `execTransactionFromModuleReturnData` is it possible to update that also?

**Comment by Aboudjem** [comment]
Thank you @zakrad for your valuable contribution. We have addressed the issues you brought to our attention and made the necessary fixes. Your input has been extremely helpful in improving our project.
