### ISSUE TITLE
Bug Report 2024-01-28

### ISSUE THREAD

**Issue by rholterhus** [bcnmy/scw-contracts#195]
I'm opening this issue to report a bug, which I'm doing based on this:

> If you've identified a bug that hasn't been reported, open a new [Issue](https://github.com/bcnmy/scw-contracts/issues/new) detailing the bug.

With this specific bug, it'd be better if the details aren't available for everyone to see, so can I send my writeup privately to the team somehow? I can do email or any other medium.

**Comment by ankurdubey521** [comment]
@Aboudjem

**Comment by rholterhus** [comment]
Thanks I just messaged on telegram. I'll close this issue
