### ISSUE TITLE
Deployment of PasskeyValidationModules/Secp256r1 to Base and Base Sepolia

### ISSUE THREAD

**Issue by dangerousfood** [bcnmy/scw-contracts#212]
Deploy and configure a version of `PasskeyValidationModules/Secp256r1.sol` to `Base` (`chainId:8453`) and `Base Sepolia` (`chainId:84532`)

https://github.com/bcnmy/scw-contracts/blob/main/contracts/smart-account/modules/PasskeyValidationModules/Secp256r1.sol

**Comment by livingrockrises** [comment]
passkey module is deployed at 0x00000c99cbbb3b0626db6ac76c00ef1839f35773 on all major EVM chains.
above contract uses Secp256r1 library.

If you just want separate library it's deployed at below addresses

base sepolia: 0x73962ef3f05f20A08207c2e02ce58a859E0B3942
base: 0x0987404beB853f24F36C76c3e18Adcad7AB44f93
